cart/urls.py
# from django.urls import url
from django.urls import re_path, path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from myshop import settings
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^orders/', include(('orders.url', 'orders'), namespace='orders')),
    path('', include('shop.urls')),
    path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
    path('accounts/profile/', user_views.profile, name='profile'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

cart/templates/cart/cart_detail.html
{% extends "shop/index.html" %}
{% load static %}
{% block link %}<link rel="stylesheet" type="text/css" href = "{% static "css/cart.css"%}"> {% endblock link %}
{% block title %}Корзина{% endblock %}



{% block content %}
    <div class="cart">
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Корзина:
            <a href="{% url "cart:cart_detail" %}">
                {{ total_items }} товаров {{ total_items|pluralize }},
                {{ cart.get_total_price }}₽
            </a>
        {% else %}
            Ваша корзина пуста.
        {% endif %}
    {% endwith %}
</div>

    <table class="table">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img height="50px" width="50px" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "images/no-image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
{#                    {% block cart_q %}#}
{#                    {{ item.quantity }}#}
{#                    {% endblock %}#}
                    <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
{#        <a href="{% url "shop:category_list" %}" class="button light">Продолжить покупки </a>#}
        <a href="{% url "orders:order_create" %}" class="btn_22">Оформить</a>
    </p>


{% endblock %}